### ISSUE TITLE
wrong argument type nil (expected String)

### ISSUE THREAD

**Issue by neumayr** [zooppa/administrate-field-simple_markdown#2]
Hey @michelegera 

Wanted to share this issue:

Some of my `description` data is `nil`. SimpleMarkdown fails to render the data. 
Workaround: Change to empty string.

```rb
wrong argument type nil (expected String)

# /gems/administrate-0.8.1/app/views/administrate/application/show.html.erb
def to_html
  markdown(html_renderer).render(data).html_safe
end
```

```consloe
# Framework trace
administrate-field-simple_markdown (0.0.4) lib/administrate/field/simple_markdown.rb:14:in `render'
administrate-field-simple_markdown (0.0.4) lib/administrate/field/simple_markdown.rb:14:in `to_html'
administrate-field-simple_markdown (0.0.4) app/views/fields/simple_markdown/_show.html.erb:12:in 
```

**Comment by michelegera** [comment]
Hey @neumayr, I’ve just [released v0.1.0](https://github.com/zooppa/administrate-field-simple_markdown/releases/tag/v0.1.0) that should fix this issue 🎉
